# Generated by Django 5.1.1 on 2024-11-22 15:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.TextField(blank=True, default='', verbose_name='ID Сессии')),
                ('login', models.TextField(default='', verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('surname', models.TextField(blank=True, verbose_name='Фамилия')),
                ('name', models.TextField(verbose_name='Имя')),
                ('middlename', models.TextField(blank=True, verbose_name='Отчество')),
                ('email', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.TextField(blank=True, verbose_name='Номер телефона')),
                ('role', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.role')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.JSONField(blank=True, default=list, verbose_name='Json')),
                ('mark_studies', models.BooleanField(blank=True, default=False, verbose_name='Оценка учеба')),
                ('comment_studies', models.TextField(blank=True, verbose_name='Комментарий учеба')),
                ('mark_science', models.BooleanField(blank=True, default=False, verbose_name='Оценка наука')),
                ('comment_science', models.TextField(blank=True, verbose_name='Комментарий наука')),
                ('mark_activities', models.BooleanField(blank=True, default=False, verbose_name='Оценка мероприятия')),
                ('comment_activities', models.TextField(blank=True, verbose_name='Комментарий мероприятия')),
                ('mark_culture', models.BooleanField(blank=True, default=False, verbose_name='Оценка культура')),
                ('comment_culture', models.TextField(blank=True, verbose_name='Комментарий культура')),
                ('mark_sport', models.BooleanField(blank=True, default=False, verbose_name='Оценка спорт')),
                ('comment_sport', models.TextField(blank=True, verbose_name='Комментарий спорт')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 22, 18, 43, 54, 627665), verbose_name='Дата')),
                ('points', models.IntegerField(blank=True, default=0, verbose_name='Баллы')),
                ('status', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='main.status')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(default='', verbose_name='Событие')),
                ('statement_copy', models.JSONField(blank=True, verbose_name='Контент')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 22, 18, 43, 54, 627665), verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.user')),
            ],
        ),
    ]
