# Generated by Django 5.1.1 on 2024-10-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('img', models.CharField(max_length=50, verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent_lesson', models.IntegerField(verbose_name='id_parent_lesson')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent_module', models.IntegerField(verbose_name='id_parent_module')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('img', models.CharField(max_length=50, verbose_name='img')),
                ('json', models.CharField(max_length=50000, verbose_name='json')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent_course', models.IntegerField(verbose_name='id_parent_course')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('img', models.CharField(max_length=50, verbose_name='img')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('role', models.CharField(max_length=50, verbose_name='role')),
                ('surname', models.CharField(max_length=50, verbose_name='surname')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('middlename', models.CharField(max_length=50, verbose_name='middlename')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(max_length=50, verbose_name='phone')),
                ('img', models.CharField(max_length=50, verbose_name='img')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='UserToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='id_user')),
                ('id_course', models.IntegerField(verbose_name='id_course')),
            ],
        ),
        migrations.CreateModel(
            name='UserToSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(verbose_name='id_user')),
                ('id_session', models.CharField(max_length=1000, verbose_name='id_session')),
            ],
        ),
        migrations.CreateModel(
            name='VideoElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_parent_lesson', models.IntegerField(verbose_name='id_parent_lesson')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('url', models.CharField(max_length=50, verbose_name='url')),
            ],
        ),
    ]
