# Generated by Django 5.1.1 on 2024-10-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(default=0, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.CharField(max_length=400, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='documentelement',
            name='url',
            field=models.CharField(max_length=400, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='img',
            field=models.CharField(max_length=400, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='module',
            name='img',
            field=models.CharField(max_length=400, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(max_length=400, verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='videoelement',
            name='url',
            field=models.CharField(max_length=400, verbose_name='url'),
        ),
    ]
