# Generated by Django 5.1.3 on 2024-11-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lesson_order_module_order_alter_course_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1, verbose_name='ID Пользователя')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('json', models.JSONField(default=list, verbose_name='Json')),
                ('mark_studies', models.BooleanField(default=False, verbose_name='Оценка учеба')),
                ('comment_studies', models.TextField(verbose_name='Комментарий учеба')),
                ('mark_science', models.BooleanField(default=False, verbose_name='Оценка наука')),
                ('comment_science', models.TextField(verbose_name='Комментарий наука')),
                ('mark_activities', models.BooleanField(default=False, verbose_name='Оценка мероприятия')),
                ('comment_activities', models.TextField(verbose_name='Комментарий мероприятия')),
                ('mark_culture', models.BooleanField(default=False, verbose_name='Оценка культура')),
                ('comment_culture', models.TextField(verbose_name='Комментарий культура')),
                ('mark_sport', models.BooleanField(default=False, verbose_name='Оценка спорт')),
                ('comment_sport', models.TextField(verbose_name='Комментарий спорт')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='DocumentElement',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='UserToCourse',
        ),
        migrations.DeleteModel(
            name='UserToSession',
        ),
        migrations.DeleteModel(
            name='VideoElement',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.TextField(default='', verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.TextField(default='', verbose_name='ID Сессии'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.TextField(verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=0, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.TextField(verbose_name='Фамилия'),
        ),
    ]
