# Generated by Django 5.1.1 on 2024-11-22 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_period_alter_log_date_alter_statement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 22, 20, 50, 13, 908318), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 22, 20, 50, 13, 908318), verbose_name='Дата'),
        ),
    ]
