# Generated by Django 5.1.3 on 2024-11-28 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_log_date_alter_statement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 28, 13, 6, 14, 516633), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 28, 13, 6, 14, 515632), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='id',
            field=models.TextField(blank=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.TextField(blank=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Идентификатор'),
        ),
    ]
