# Generated by Django 5.1.1 on 2024-12-04 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_statement_cashe_status_alter_log_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='data',
            field=models.TextField(default='', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 4, 20, 31, 29, 241490), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 4, 20, 31, 29, 240490), verbose_name='Дата'),
        ),
    ]
