# Generated by Django 5.1.1 on 2024-12-04 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_log_data_alter_log_date_alter_statement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statement',
            old_name='cashe_status',
            new_name='cache_status',
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 4, 20, 47, 26, 831504), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 12, 4, 20, 47, 26, 830503), verbose_name='Дата'),
        ),
    ]
