# Generated by Django 5.1.1 on 2025-05-27 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_cache_status_statement_old_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.TextField(blank=True, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='user',
            name='inst',
            field=models.TextField(blank=True, verbose_name='Институт'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 27, 12, 51, 6, 226017), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 27, 12, 51, 6, 226017), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='mark_activities',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Оценка мероприятия'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='mark_culture',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Оценка культура'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='mark_science',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Оценка наука'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='mark_sport',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Оценка спорт'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='mark_studies',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Оценка учеба'),
        ),
    ]
