# Generated by Django 5.2.3 on 2025-06-17 14:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_group_user_inst_alter_log_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 17, 17, 37, 44, 154855), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 17, 17, 37, 44, 154855), verbose_name='Дата'),
        ),
    ]
